---
- hosts: all
  remote_user: vagrant

  tasks:
  - include: tasks/linux/prepare.yml
  - include: tasks/apache/start.yml
  - include: tasks/java/install.yml
  - include: tasks/aem/setup.yml
#  - include: tasks/aem/initial-run.yml
