---
# tasks file for apache-install--mac
 - name: Install apache httpd
   homebrew: name=apache2 state=present
   become: yes
   become_method: sudo
 - name: make sure apache is running
   service: name=apache2 state=started
   become: yes
   become_method: sudo
   #
