---
- hosts: all
  remote_user: vagrant
  tasks:
#  - apt: name=apache2 state=present
#  - apt: name=apache2 state=absent
#    become: yes
#    become_method: sudo
  - service: name=apache2 state=started
    become: yes
    become_method: sudo